version: "3"
services:
  web:
    build: .
    ports:
      - "7575:7575"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dbuser
      DB_PASSWORD: dbpassword
      DB_NAME: newsletter
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: newsletter
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
